name: Integration Test
"on": [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        uses: gijswobben/flake8-action@main
        with:
          flake8_config: |
            [flake8]
            exclude = examples/
            max-line-length = 88
            extend-ignore =
                # See https://github.com/PyCQA/pycodestyle/issues/373
                E203,
          strict: true
          additional_packages: pep8-naming==0.13.2 flake8-annotations==2.9.1 darglint==1.8.1

      - uses: actions/checkout@master
      - name: Bad code test
        uses: gijswobben/flake8-action@main
        continue-on-error: true
        with:
          flake8_config: |
            [flake8]
            filename = **/examples/incorrect_code.py
          strict: true
          additional_packages: pep8-naming==0.13.2 flake8-annotations==2.9.1 darglint==1.8.1
      - name: Invert success and failure
        run: if [[ ${{ steps.lint-incorrect.outcome }} == "failure" ]]; then exit 0; else exit 1; fi
